name: my_todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.4
  go_router: ^10.1.2
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.16.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
